spring.application.name=easy-expenses-api
spring.profiles.active=dev

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

token.secret=${JWT_SECRET}
token.issuer=easy-expenses-api-security-layer
token.audience=easy-expenses-api
token.access-token-expiration=15m
token.refresh-token-expiration=7d