spring.application.name=easy-expenses-api
spring.profiles.active=dev

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

jwt.secret=${JWT_SECRET}