spring.datasource.url=jdbc:postgresql://localhost:5432/easy-expenses-db
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect