spring.application.name=easy-expenses-api
spring.profiles.active=${SPRING_PROFILES_ACTIVE}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH_PROVIDER_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.audiences=${AUTH_PROVIDER_AUDIENCE}


spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.user=${DB_USERNAME}
spring.flyway.password=${DB_PASSWORD}
spring.flyway.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.flyway.locations=classpath:db/migration